# -*- coding: utf-8 -*-
"""CSE110Lab7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yIB7q_BFgWcBCATzMoKhO6Ss-z2ENDW
"""

#1(selection sort-asending)
def lst(list1):
  for i in range(len(list1)-1):
    min=list1[i]
    min_idx=i
    for j in range(i+1,(len(list1))):
      if min>list1[j]:
        min=list1[j]
        min_idx=j
    list1[i],list1[min_idx]=list1[min_idx],list1[i]
  return list1

lst([10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29])

#1(Bubble sort-asending)
def lst(list1):
  for i in range(len(list1)-1):
    for j in range(len(list1)-1):
      if list1[j]>list1[j+1]:
        list1[j],list1[j+1]=list1[j+1],list1[j]
  return list1
my_list=[10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
lst(my_list)

#2(selection sort-asending)
def lst(list1):
  for i in range(len(list1)-1):
    min=list1[i]
    min_idx=i
    for j in range(i+1,(len(list1))):
      if min>list1[j]:
        min=list1[j]
        min_idx=j
    list1[i],list1[min_idx]=list1[min_idx],list1[i]
  return list1

my_list=[10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
lst(my_list)

#3(Bubble sort-desending)
def lst(list1):
  for i in range(len(list1)-1):
    for j in range(len(list1)-1):
      if list1[j]<list1[j+1]:
        list1[j],list1[j+1]=list1[j+1],list1[j]
  return list1

my_list = [10, 1, 20, 3, 6, 2, 5, 11, 15, 2, 12, 14, 17, 18, 29]
lst(my_list)

#4
def sitting_list(list1):  
    for x in range(len(list1)):
        for y in range(x,len(list1)):
            if x%2==0 and y%2==0:
                if list1[x]>list1[y]:
                    list1[x],list1[y]=list1[y],list1[x]
                
    for z in range(len(list1)):
        for i in range(z,len(list1)):
            if z%2!=0 and i%2!=0:
                if list1[z]<list1[i]:
                    list1[z],list1[i]=list1[i],list1[z]
    return list1 

sitting_list = [10,30,20,70,11,15,22,16,58,100,12,56,70,80]            
print(sitting_list)

#5
def marks(lst):

  str1=input("Enter your desired course:")
  dictionary={'CSE110':1,'PHY111':2,'MAT110':3}
  for x in range(len(lst)-1):
      for y in range(len(lst)-1-x):
          if lst[y][dictionary[str1]] < lst[y+1][dictionary[str1]]:
              lst[y],lst[y+1] = lst[y+1],lst[y]

  for x in lst:
      print(x[0])


marks([["Alan", 95, 87, 91],["Turing", 92, 90, 83],["Elon", 87, 92, 80],["Musk", 85, 94, 90]])

#Solution of Task-6
my_list=[4, 2, 3, 1, 6, 5]
list1=my_list.copy()
count=0

for x in range(0,len(my_list)):
  min_val=my_list[x]
  min_index=x
  for y in range(x+1,len(my_list)):
    if my_list[y]<min_val:
      min_val=my_list[y]
      min_index=y
  temp=min_val
  my_list[min_index]=my_list[x]
  my_list[x]=temp


for z in range(len(my_list)):
  if my_list[z]!=list1[z]:
    count+=1
print(count)

#Solution of Task-7
def my_function(list1,list2):
    list3=[]
    for x in list1:
        list3.append(int(x))
    for x in list2:
        list3.append(int(x))
    for x in range(len(list3)):
        for y in range(len(list3)-1):
            if list3[y+1]<list3[y]:
                list3[y+1],list3[y]=list3[y],list3[y+1]
    print("Sorted list =",list3)            
    if len(list3)%2!=0:
        median=list3[len(list3)//2]
    else:
        num1=list3[len(list3)//2-1]
        num2=list3[(len(list3)//2)]
        median=(num1+num2)/2
    print("Median =", median)            
    
list1= input("Enter the first list:")[1:-1].split(", ")
list2= input("Enter the second list:")[1:-1].split(", ")
my_function(list1,list2)

#Solution of Task-8
list1= input("Enter the list:").replace('[','').replace(']','').replace(' ','').split(',')
temp_list=[int(x) for x in list1]

for x in range(len(temp_list)-1):
    for y in range(len(temp_list)-x-1):
        if temp_list[y]>temp_list[y+1]:
            temp_list[y],temp_list[y+1]=temp_list[y+1],temp_list[y]

left_ind=0 
right_ind=len(temp_list)-1
min_sum=temp_list[left_ind] + temp_list[right_ind]
left_val=temp_list[left_ind]
right_val=temp_list[right_ind]

while left_ind < right_ind:
    sum=temp_list[left_ind] + temp_list[right_ind]
    
    if abs(sum)<abs(min_sum):
        min_sum=sum
        left_val=temp_list[left_ind]
        right_val=temp_list[right_ind]
        
    if sum<0:
        left_ind+= 1
    elif sum>0:
        right_ind-= 1
    else:
        break
    
print('Two pairs which have the smallest sum =',right_val,'and',left_val)

#Solution of Task-9
import math
def my_function(points):
    list1=[]
    dict1={}
    min1=""
    min2=0
    for x in points:
        num1=x[0]
        num2=x[1]
        dist=math.sqrt((num1**2 + (num2**2)))
        list1.append(dist)
    for x in range(len(points)):
        dict1[list1[x]]=points[x]
        
    for x in range(len(list1)):
        for y in range(len(list1)-1):
            if list1[y+1]<list1[y]:
                list1[y],list1[y+1]=list1[y+1],list1[y]
    for x in dict1:
        if x==list1[0]:
            min2=x
            min1=dict1[x]
    print("Minimum distance =", min2)        
    print("Here the closest point is",min1,"which has a distance of",min2,"from the origin.")       
points=[(5,3),(2,9),(-2,7),(-3,-4),(0,6),(7,-2)]
my_function(points)